### PR TITLE
Added programme agenda layout

### PR DESCRIPTION
**Pull request by AverageMarcus**
Added both programme and speakers. 

Live preview: https://5c922057.kubehuddle.pages.dev/2022/

### CODE REVIEW

**Comment by rawkode** [comment]
@AverageMarcus Can this be merged as is, or should I add the schedule first?

**Comment by AverageMarcus** [comment]
Can be merged as is. Wont actually show up until schedule is populated :)

**Comment by rawkode** [comment]
@AverageMarcus is this ready to deploy?

**Comment by AverageMarcus** [comment]
Yeah. It’s got all the details from the sessionize api. Guess you’ll need to update as more confirm

**Pull request merged**
